controllers/ClasificacionController.php
<?php

namespace app\controllers;

//use app\controllers\Controller;
use yii\filters\AccessControl;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Ciclista;
use app\models\Etapa;
use app\models\Lleva;
use app\models\Maillot;
use app\models\Puerto;
use app\models\Equipo;
use yii\web\View;
use yii\data\SqlDataProvider;
use yii\web\Controller;


/* 
 
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/Scripting/EmptyPHP.php to edit this template
*/

class ClasificacionController extends Controller
{
    public function actionIndex()
    {
        // Resto de la acción
        return $this->render('index', [
            'consulta' => new SqlDataProvider([
                'sql' => 'SELECT DISTINCT e.numetapa, e.salida, e.llegada, l.dorsal, c.nombre, m.tipo
                      FROM maillot m INNER JOIN lleva l INNER JOIN ciclista c INNER JOIN etapa e  ON m.código = l.código 
                      AND l.numetapa = e.numetapa  AND l.dorsal = c.dorsal ORDER BY e.numetapa',
            ]),

            'campos' => ['numetapa', 'salida', 'llegada', 'dorsal', 'nombre', 'tipo'],

        ]);
    }
}

controllers/EquipoController.php
<?php

namespace app\controllers;

use app\models\Equipo;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EquipoController implements the CRUD actions for Equipo model.
 */
class EquipoController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Equipo models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Equipo::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'nomequipo' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Equipo model.
     * @param string $nomequipo Nomequipo
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($nomequipo)
    {
        return $this->render('view', [
            'model' => $this->findModel($nomequipo),
        ]);
    }

    /**
     * Creates a new Equipo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Equipo();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'nomequipo' => $model->nomequipo]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Equipo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $nomequipo Nomequipo
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($nomequipo)
    {
        $model = $this->findModel($nomequipo);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'nomequipo' => $model->nomequipo]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Equipo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $nomequipo Nomequipo
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($nomequipo)
    {
        $this->findModel($nomequipo)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Equipo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $nomequipo Nomequipo
     * @return Equipo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($nomequipo)
    {
        if (($model = Equipo::findOne(['nomequipo' => $nomequipo])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/EtapaController.php
<?php

namespace app\controllers;

use app\models\Etapa;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\Ciclista;
use yii\data\SqlDataProvider;
/**
 * EtapaController implements the CRUD actions for Etapa model.
 */
class EtapaController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Etapa models.
     *
     * @return string
     */
    public function actionIndex()
    {
         return $this->render('index', [
            'etapa1' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 1 AND dorsal = dorsal",
            ]),
            "campos1" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
             
              'etapa2' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 2 AND dorsal = dorsal",
            ]),
            "campos2" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
             
             
             'etapa3' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 3 AND dorsal = dorsal",
            ]),
            "campos3" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
             
             'etapa4' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 4 AND dorsal = dorsal",
            ]),
            "campos4" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
             
             'etapa5' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 5 AND dorsal = dorsal",
            ]),
            "campos5" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
             
             'etapa6' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 6 AND dorsal = dorsal",
            ]),
            "campos6" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
             
             'etapa7' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 7 AND dorsal = dorsal",
            ]),
            "campos7" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
             
             'etapa8' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 8 AND dorsal = dorsal",
            ]),
            "campos8" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
             
             'etapa9' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 9 AND dorsal = dorsal",
            ]),
            "campos9" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
             
             'etapa10' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 10 AND dorsal = dorsal",
            ]),
            "campos10" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
             
             'etapa11' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 11 AND dorsal = dorsal",
            ]),
            "campos11" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
             
             'etapa12' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 12 AND dorsal = dorsal",
            ]),
            "campos12" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
             
             'etapa13' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 13 AND dorsal = dorsal",
            ]),
            "campos13" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
             
             'etapa14' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 14 AND dorsal = dorsal",
            ]),
            "campos14" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
             
             'etapa15' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 15 AND dorsal = dorsal",
            ]),
            "campos15" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
             
             'etapa16' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 16 AND dorsal = dorsal",
            ]),
            "campos16" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
             
             'etapa17' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 17 AND dorsal = dorsal",
            ]),
            "campos17" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
             
             'etapa18' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 18 AND dorsal = dorsal",
            ]),
            "campos18" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
             
             'etapa19' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 19 AND dorsal = dorsal",
            ]),
            "campos19" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
             
             'etapa20' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 20 AND dorsal = dorsal",
            ]),
            "campos20" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
             
             'etapa21' => new SqlDataProvider ([
                "sql" => "select salida, llegada, kms,dorsal, nombre from etapa  INNER JOIN ciclista  USING(dorsal) where numetapa = 21 AND dorsal = dorsal",
            ]),
            "campos21" => ["salida" , "llegada", "kms", "dorsal", "nombre"],
        ]);
    }

    /**
     * Displays a single Etapa model.
     * @param int $numetapa Numetapa
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($numetapa)
    {
        return $this->render('view', [
            'model' => $this->findModel($numetapa),
        ]);
    }

    /**
     * Creates a new Etapa model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Etapa();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'numetapa' => $model->numetapa]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Etapa model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $numetapa Numetapa
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($numetapa)
    {
        $model = $this->findModel($numetapa);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'numetapa' => $model->numetapa]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Etapa model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $numetapa Numetapa
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($numetapa)
    {
        $this->findModel($numetapa)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Etapa model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $numetapa Numetapa
     * @return Etapa the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($numetapa)
    {
        if (($model = Etapa::findOne(['numetapa' => $numetapa])) !== null) {
            return $model;
        }

views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;



AppAsset::register($this);

$this->registerCsrfMetaTags();
$this->registerMetaTag(['charset' => Yii::$app->charset], 'charset');
$this->registerMetaTag(['name' => 'viewport', 'content' => 'width=device-width, initial-scale=1, shrink-to-fit=no']);
$this->registerMetaTag(['name' => 'description', 'content' => $this->params['meta_description'] ?? '']);
$this->registerMetaTag(['name' => 'keywords', 'content' => $this->params['meta_keywords'] ?? '']);
$this->registerLinkTag(['rel' => 'icon', 'type' => 'image/x-icon', 'href' => Yii::getAlias('@web/img/logo.ico')]);
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<?= Html::csrfMetaTags() ?>

<head>
    <title>La Vuelta Al Pasado</title> <!-- Título predeterminado -->
    <?php $this->head() ?>
</head>

<body class="d-flex flex-column h-100">
    <?php $this->beginBody() ?>

    <header id="header">
        <?php
        NavBar::begin([
            'brandLabel' => '<img src="' . Yii::getAlias('@web/img/logo.png') . '" alt="Logo" class="logo">',
            'brandUrl' => Yii::$app->homeUrl,
            'options' => ['class' => 'navbar-expand-md fixed-top']
        ]);
        echo '<div class="nav-container w-100">';
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav'],
            'items' => [
                '<div class="menu-items">
                <div class="text-container">
                    <div class="navbar-title">La Vuelta</div>
                    <div class="navbar-subtitle">Al Pasado</div>
                </div>
                <div class="menu-links">
                    <span>' . Html::a('Inicio', ['/site/index'], ['class' => 'nav-link']) . '</span>
                    <span>' . Html::a('Equipos', ['/equipo/index'], ['class' => 'nav-link']) . '</span>
                    <span>' . Html::a('Etapas', ['/etapa/index'], ['class' => 'nav-link']) . '</span>
                    <span>' . Html::a('Clasificacion', ['/clasificacion/index'], ['class' => 'nav-link']) . '</span>
                    <span>' . Html::a('Puertos', ['/puerto/index'], ['class' => 'nav-link']) . '</span>
                    <span>' . (Yii::$app->user->isGuest ?
                    Html::a('Curiosidades', ['/curiosidades/index'], ['class' => 'nav-link']) :
                    Html::beginForm(['/site/logout'], 'post')
                    . Html::submitButton(
                        'Logout (' . Yii::$app->user->identity->username . ')',
                        ['class' => 'nav-link btn btn-link logout']
                    )
                    . Html::endForm()) . '</span>
                </div>
            </div>',
                '<div class="social-links">
                <span>' . Html::a('<i class="fab fa-gitlab"></i>', 'https://gitlab.com/Proyecto4AdaLovelace/ada-lovelace-ciclistas', ['class' => 'nav-link']) . '</span>
                <span>' . Html::a('<i class="fa-brands fa-linkedin-in"></i>', '#', ['class' => 'nav-link']) . '</span>
            </div>',
            ]
        ]);
        echo '</div>';
        NavBar::end();
        ?>
    </header>






    <main role="main" class="flex-shrink-0">
        <div class="container">
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
            <?= Alert::widget() ?>
            <?= $content ?>
        </div>
    </main>

    <footer id="footer" class="mt-auto py-3">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 text-center text-md-start text-center text-secondary footer-info">&copy; Ada Lovelace <?= date('Y') ?></div>
            </div>
        </div>
    </footer>

    <?php $this->endBody() ?>
</body>

</html>
<?php $this->endPage() ?>